import { CourseId } from "../types/Courses";

export const courses: CourseId[] = [
  "computer_science",
  "software_engineering",
  "information_systems",
  "data_science",
  "artificial_intelligence",
  "cyber_security",
  "game_development",
  "computer_engineering",
  "electrical_engineering",
  "mechanical_engineering",
  "civil_engineering",
  "architecture",
  "business_administration",
  "economics",
  "accounting",
  "marketing",
  "law",
  "medicine",
  "nursing",
  "pharmacy",
  "psychology",
  "biology",
  "physics",
  "chemistry",
  "mathematics",
  "statistics",
  "journalism",
  "graphic_design",
  "education",
  "international_relations",
];
