import type { Options } from "@dicebear/avataaars";

export const AVATAR_OPTIONS: Options = {
  style: ["circle"],
  top: [
    "bun",
    "dreads01",
    "dreads02",
    "frizzle",
    "shaggy",
    "shortCurly",
    "shortFlat",
    "shortRound",
    "shortWaved",
    "sides",
    "theCaesar",
    "theCaesarAndSidePart",
    "fro",
  ],
  accessoriesProbability: 0,
  facialHair: [
    "beardLight",
    "beardMedium",
    "beardMajestic",
    "moustacheFancy",
    "moustacheMagnum",
  ],
  facialHairProbability: 40,
  clothing: [
    "graphicShirt",
    "hoodie",
    "shirtCrewNeck",
    "shirtScoopNeck",
    "shirtVNeck",
    "collarAndSweater",
  ],
  eyes: ["closed", "default", "happy", "side", "squint", "surprised", "wink"],
  eyebrows: [
    "angryNatural",
    "defaultNatural",
    "flatNatural",
    "raisedExcitedNatural",
    "sadConcernedNatural",
    "default",
    "raisedExcited",
  ],
  mouth: [
    "concerned",
    "default",
    "grimace",
    "sad",
    "serious",
    "smile",
    "twinkle",
  ],
  backgroundColor: ["b6e3f4", "c0aede", "d1d4f9", "ffd5dc", "ffdfbf"],
};
